// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/nopt/nopt.d.ts
declare module "nopt" {

	interface CommandData {
		[key: string]: string
	}

	interface TypeDefs {
		[key: string]: TypeInfo
	}

	interface TypeInfo {
		type: Object
		validate: (data: CommandData, k: string, val: string) => boolean
	}

	namespace nopt {
		export function clean(data: CommandData, types: FlagTypeMap, typeDefs?: TypeDefs): string
		export var typeDefs: TypeDefs
	}

	interface FlagTypeMap {
		[k: string]: Object
	}

	interface ShortFlags {
		[k: string]: string[]|string
	}

	function nopt(types: FlagTypeMap, shorthands?: ShortFlags, args?: string[], slice?: number): OptionsParsed

	interface OptionsParsed {
		[k: string]: any
		argv: {
			remain: string[]
			cooked: string[]
			original: string[]
		}
	}

	export = nopt
}
